name: Frontend CI/CD with Railway

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ESIEA-5A-QualiteLogicielle-Car-Management-Front/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ESIEA-5A-QualiteLogicielle-Car-Management-Front/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Vérification basique des fichiers HTML
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./ESIEA-5A-QualiteLogicielle-Car-Management-Front/src/main/webapp/
          
      # Optionnel : Ajout d'un linter JavaScript si vous voulez
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install ESLint
        run: |
          cd ESIEA-5A-QualiteLogicielle-Car-Management-Front
          npm init -y
          npm install eslint --save-dev
          npx eslint --init
          
      - name: Run ESLint
        run: |
          cd ESIEA-5A-QualiteLogicielle-Car-Management-Front
          npx eslint src/main/webapp/**/*.js

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy to Railway
        working-directory: ./ESIEA-5A-QualiteLogicielle-Car-Management-Front
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up